apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv 
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  hostPath:
    path: /mnt/data/prometheus-pv
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: gitlab
    name: gitlab-prometheus-server
  storageClassName: manual
