apiVersion: v1
kind: PersistentVolume
metadata:
  name: repository-pv
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  hostPath:
    path: /mnt/data/repository-pv
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: gitlab
    name: repo-data-gitlab-gitaly-0
  storageClassName: manual
