apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: <firewall-ip>
      user: root
      port: 22
    role: controller+worker
    hostname: master
    hooks:
      apply:
        before:
          - rm -r /mnt/data/*
          - mkdir -p /mnt/data/postgres-pv
          - mkdir -p /mnt/data/minio-pv
          - mkdir -p /mnt/data/prometheus-pv
          - mkdir -p /mnt/data/redis-pv
          - mkdir -p /mnt/data/repository-pv
          - chmod 777 /mnt/data/*
  - ssh:
      address: <worker-0-local-ip>
      user: root
      port: 22
      bastion:
        address: <firewall-ip>
        port: 22
        user: root
    role: worker
    hostname: worker-0
    hooks:
      apply:
        before:
          - rm -r /mnt/data/*
          - mkdir -p /mnt/data/postgres-pv
          - mkdir -p /mnt/data/minio-pv
          - mkdir -p /mnt/data/prometheus-pv
          - mkdir -p /mnt/data/redis-pv
          - mkdir -p /mnt/data/repository-pv
          - chmod 777 /mnt/data/*
  - ssh:
      address: <worker-0-local-ip>
      user: root
      port: 22
      bastion:
        address: <firewall-ip>
        user: root
        port: 22
    role: worker
    hostname: worker-1
    hooks:
      apply:
        before:
          - rm -r /mnt/data/*
          - mkdir -p /mnt/data/postgres-pv
          - mkdir -p /mnt/data/minio-pv
          - mkdir -p /mnt/data/prometheus-pv
          - mkdir -p /mnt/data/redis-pv
          - mkdir -p /mnt/data/repository-pv
          - chmod 777 /mnt/data/*
  k0s:
    version: 1.23.3+k0s.1
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
        images:
          calico:
            flexvolume:
              image: docker.io/calico/pod2daemon-flexvol
              version: v3.21.2
            cni:
              image: docker.io/calico/cni
              version: v3.21.2
            kubecontrollers:
              image: docker.io/calico/kube-controllers
              version: v3.21.2
            node:
              image: docker.io/calico/node
              version: v3.21.2
          coredns:
            image: k8s.gcr.io/coredns/coredns
            version: v1.7.0
          default_pull_policy: IfNotPresent
          konnectivity:
            image: quay.io/k0sproject/apiserver-network-proxy-agent
            version: 0.0.27-k0s2
          kubeproxy:
            image: k8s.gcr.io/kube-proxy
            version: v1.23.3
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          provider: calico
          calico: 
            mode: vxlan
            vxlanPort: 4789
            vxlanVNI: 4096
            mtu: 0
            wireguard: false
            flexVolumeDriverPath: /usr/libexec/k0s/kubelet-plugins/volume/exec/nodeagent~uds
            withWindowsNodes: false
            overlay: Always
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: true
