apiVersion: v1
kind: Service
metadata:
  namespace: gitlab
  name: nginx-ingress-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx-ingress
    component: controller
    release: gitlab
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      appProtocol: https
      port: 443
      targetPort: https
    - name: gitlab-shell
      protocol: TCP
      port: 22
      targetPort: gitlab-shell
